var gulp = require('gulp'),
    browserify = require('gulp-browserify'),
    babel = require('gulp-babel'),
    clean = require('gulp-clean'),
    rename = require('gulp-rename'),
    watch = require('gulp-watch'),
    minify = require('gulp-minify'),
    mocha = require('gulp-mocha');

/**
 * Removes all files generated by gulp.
 */
gulp.task('clean', function() {
    return gulp.src('dist')
        .pipe(clean({force: true}));
});

/**
 * Compiles JSX files into normal JavaScript.
 */
gulp.task('compile', ['clean'], function() {
    return gulp.src('src/*.js')
        .pipe(babel())
        .pipe(gulp.dest('dist/js'));
});

/**
 * Packages all files into one big JavaScript file usable in the browser.
 */
gulp.task('browserify', ['clean'], function() {
    return gulp.src('src/index.js')
        .pipe(browserify({
            transform: ['babelify'],
            standalone: 'FormValidation'
        }))
        .pipe(rename('react-form-validation.js'))
        .pipe(gulp.dest('dist'));
});

/**
 * Makes the javascript file smaller.
 */
gulp.task('minify', ['browserify'], function() {
    return gulp.src('dist/react-form-validation.js')
        .pipe(minify())
        .pipe(gulp.dest('dist'))
});

/**
 * Watch files in src and rebuild project if they change.
 */
gulp.task('watch', ['build'], function() {
    return gulp.watch(['src/**/*'], ['build']);
});

/**
 * Watch files in src and rebuild project if they change.
 */
gulp.task('test', function() {
    // setup babel
    require("babel-polyfill");
    require('babel-register')();

    return gulp.src(['test/**/*-test.js'])
        .pipe(mocha());
});

/**
 * Default task.
 */
gulp.task('build', ['compile', 'browserify', 'minify']);
