var gulp = require('gulp'),
    browserify = require('gulp-browserify'),
    babel = require('gulp-babel'),
    clean = require('gulp-clean'),
    rename = require('gulp-rename'),
    watch = require('gulp-watch');

/**
 * Removes all files generated by gulp.
 */
gulp.task('clean', function() {
    return gulp.src('dist')
        .pipe(clean({force: true}));
});

/**
 * Compiles JSX files into normal JavaScript.
 */
gulp.task('compile', ['clean'], function() {
    return gulp.src('src/*.js')
        .pipe(babel())
        .pipe(gulp.dest('dist/js'));
});

/**
 * Packages all files into one big JavaScript file usable in the browser.
 */
gulp.task('browserify', ['clean'], function() {
    return gulp.src('src/form.js')
        .pipe(browserify({
            transform: ['babelify'],
            standalone: 'FormValidation'
        }))
        .pipe(rename('react-form-validation.js'))
        .pipe(gulp.dest('dist'));
});

/**
 * Copies the files from the example to the dist directory
 */
gulp.task('example-copy', ['clean'], function() {
    // copy the html file
    return gulp.src('example/*')
        .pipe(gulp.dest('dist/example'))
        .on('error', function(error) {
            console.warn('failed to copy files', error);
        });
});

/**
 * Packages all files into one big JavaScript file usable in the browser.
 */
gulp.task('example-build', ['example-copy'], function() {
    // compile and browserify the javascript
    return gulp.src('example/index.js')
        .pipe(browserify({
            transform: ['babelify']
        }))
        .on('error', function(error) {
            console.log(error.stack.replace(/[ ]+at .*\n?/g, ''));
        })
        .pipe(rename('index.js'))
        .pipe(gulp.dest('dist/example'));
});

/**
 * Compiles and packages the example files.
 */
gulp.task('example-dev', ['example-build'], function() {
    gulp.watch(['example/**/*', 'src/**/*'], ['example-build']);
});

/**
 * Default task.
 */
gulp.task('default', ['compile', 'browserify', 'example']);
