var gulp = require('gulp'),
    browserify = require('gulp-browserify'),
    babel = require('gulp-babel'),
    clean = require('gulp-clean'),
    rename = require('gulp-rename'),
    watch = require('gulp-watch');

/**
 * Removes all files generated by gulp.
 */
gulp.task('clean', function() {
    return gulp.src('dist')
        .pipe(clean({force: true}));
});

/**
 * Compiles JSX files into normal JavaScript.
 */
gulp.task('compile', ['clean'], function() {
    return gulp.src('src/*.js')
        .pipe(babel())
        .pipe(gulp.dest('dist/js'));
});

/**
 * Packages all files into one big JavaScript file usable in the browser.
 */
gulp.task('browserify', ['clean'], function() {
    return gulp.src('src/index.js')
        .pipe(browserify({
            transform: ['babelify'],
            standalone: 'FormValidation'
        }))
        .pipe(rename('react-form-validation.js'))
        .pipe(gulp.dest('dist'));
});

/**
 * Watch files in src and rebuild project if they change.
 */
gulp.task('watch', ['build'], function() {
    gulp.watch(['src/**/*'], ['build']);
});

/**
 * Default task.
 */
gulp.task('build', ['compile', 'browserify']);
